"""message

Revision ID: e19c5245458b
Revises: 62557f60cfe8
Create Date: 2023-09-14 11:24:43.434415

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e19c5245458b'
down_revision = '62557f60cfe8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sounds', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sounds', schema=None) as batch_op:
        batch_op.drop_column('image')

    # ### end Alembic commands ###
